### ISSUE TITLE
Western software exceptionalism causes failure to account for other languages

### ISSUE THREAD

**Issue by freemin7** [alphabi/alpha.bi#1]
Liebe Grüße aus Deutschland,
Greetings from Germany,

i find it very bothersome that yet another great idea in computer science (like encoding text in binary) is poisoned by a failure to account for other languages or writing systems.
This will certainly hamper world-wide adoption and i predict that in part because of this it will not archive the wide spread support and use the idea deserves. The encoding in its current form does not allow to represent Ä or 銀.

Furthermore i currently see problems regarding the use of an unspecified dictionary. This more often than not leads to sub-optimal pseudo standards which are often bound to the culture they were created in. I propose to not use an English based dictionary but a Toki pona based one. Toki pona uses only a subset of the Latin alphabet namely {A, E, I, J, R, L, M, N, O, P, S T, U, W} and has less than 256 words. This could drastically shorten the encoding time from binary to text representation. Additionally just like this encoding the Toki Pona lacks the concept of capital letters. It seems that for many reasons Toki Pona would be a natural fit.

I propose an additional symbol of 128 1s to start and end a arbitrary binary encoding block. The binary data inside it should be encoded as zero (1011) and  one (110) to prevent further confusion.

**Comment by stuartpb** [comment]
Of course, it's the other way around (Unicode encodes text as binary - alphabi encodes *binary* as *text*), and alphabi only specifies behaviors around *characters*, not dictionaries, but for procedures for encoding binary using characters beyond the Basic Latin alphabet, check out https://github.com/alphabi/alphabi-rulesets. Currently, we have:

- Naive Alphabi, in which "Ä" is ignored altogether (this is the form implemented by experiment-a0z1's [dictgen.lua](https://github.com/alphabi/experiment-a0z1/blob/master/dictgen.lua))
- Superficial Alphabi, in which "Ä" is interpreted as being identical to "A", and the Cyrillic "С" (consistently included in the second half of Cyrillic alphabets) is interpreted as being identical to the Latin "C" (this requires Unicode normalization facilities to implement)
- Presumptuous Alphabi (in development), in which characters are interpreted based on their code point's position within their Unicode block (so the Cyrillic О is interpreted as a 0, based on its position in the Russian alphabet, even though О is distinctly in the *second* half of the Ukranian alphabet, where characters are interpreted as 1)

International users are invited to contribute rulesets more appropriate for their own local alphabets, via https://github.com/alphabi/alphabi-rulesets/pulls: I don't presume myself qualified to write such rulesets on their behalf.
